#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  #remote_user: root
  become: yes
  become_method: sudo

  tasks:
  - name: Add OpenStack release package (CentOS)
    package: name="centos-release-openstack-pike" state=present
    when: >
        ansible_distribution == 'CentOS'

  - name: Install 'openstackclient'
    package: name=python-openstackclient state=installed

  - name: Install 'stack' helper tool
    get_url: url=https://raw.githubusercontent.com/gbraad/openstack-tools/master/stack dest=/sbin/stack mode=0755
